export const CAMPUS_LANDMARKS = [
  'Block 1', 'Block 2', 'Block 3', 'Block 4', 'Block 5',
  'Block 6', 'Block 7', 'Block 8', 'Block 9', 'Block 10',
  'Block 11', 'Block 12', 'Block 13', 'Block 14', 'Block 15',
  'Block 16', 'Block 17', 'Block 18', 'Block 19', 'Block 20', 'Block 21',
  'COE Block',
  'New CSE Block',
  'MBA Block',
  'Law Block',
  'Pharmacy Block',
  'Dental Block',
  'ECE Block',
  'IT Block',
  'EEE Block',
  'Old CSE Block',
  'Admin Block',
  'IRC Block',
  'Sathyabama Research Block',
  'Specialization Block',
  'Appa Hostel',
  'Gopalakrishnan Hostel',
  'Antony Hostel',
  'MGR Hostel',
  'Canteen Block',
  'Main Mess Block',
  'PG Mess Block',
  'Indian Bank Block',
  'Library Block',
  'Sathyabama Indoor Auditorium',
  'MJ Auditorium',
] as const;

export type CampusLandmark = typeof CAMPUS_LANDMARKS[number];
